import type { Product } from "@/types";
import { withGuaranteedImages } from "@/lib/product-images";

type ProductSeed = Omit<Product, "id" | "slug" | "sku">;

function slugify(text: string): string {
  const cleaned = text.replace(/[а-яА-ЯёЁ]/g, " ").trim();
  return cleaned
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "");
}

const sets: ProductSeed[] = [
  {
    name: { ru: "Костюм Premium Black", tj: "Костюми Premium Black" },
    description: {
      ru: "Премиальный двубортный костюм из итальянской шерсти Super 120s. Безупречный крой, шёлковая подкладка.",
      tj: "Костюми премиум аз пашми Италияи Super 120s. Бури беҳамто ва остари абрӣ.",
    },
    category: "sets",
    brand: "Golib",
    price: 2890,
    oldPrice: 3490,
    images: [
      "https://images.unsplash.com/photo-1594938298603-c8148c4dae35?w=800&q=80",
      "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=800&q=80",
    ],
    videoUrl: "https://assets.mixkit.co/videos/preview/mixkit-man-posing-in-a-studio-34496-large.mp4",
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: [
      { name: "Black", hex: "#0a0a0a" },
      { name: "Charcoal", hex: "#36454F" },
    ],
    stock: 8,
    isNew: true,
    isPopular: true,
    viewsCount: 342,
    boughtToday: 12,
  },
  {
    name: { ru: "Костюм Navy Executive", tj: "Костюми Navy Executive" },
    description: {
      ru: "Классический тёмно-синий костюм для деловых встреч. Ткань с лёгкой текстурой, идеальная посадка по фигуре.",
      tj: "Костюми классикии кабуди торик барои мулоқотҳои тиҷорӣ. Матои бо текстураи сабук.",
    },
    category: "sets",
    brand: "Golib",
    price: 2590,
    oldPrice: 3190,
    images: [
      "https://images.unsplash.com/photo-1617137968427-85924c800a41?w=800&q=80",
      "https://images.unsplash.com/photo-1624227732930-1c8a28058103?w=800&q=80",
    ],
    sizes: ["S", "M", "L", "XL"],
    colors: [{ name: "Navy", hex: "#1B2838" }],
    stock: 11,
    isPopular: true,
    viewsCount: 218,
    boughtToday: 7,
  },
  {
    name: { ru: "Костюм Slim Fit Grey", tj: "Костюми Slim Fit Grey" },
    description: {
      ru: "Современный slim-fit костюм серого меланжа. Универсальный выбор для офиса и мероприятий.",
      tj: "Костюми муосири slim-fit бо ранги хокистарӣ. Интихоби универсалӣ барои офис.",
    },
    category: "sets",
    brand: "Golib",
    price: 2290,
    images: [
      "https://images.unsplash.com/photo-1593030761757-71faebb0799c?w=800&q=80",
      "https://images.unsplash.com/photo-1560250097-0b93528c311a?w=800&q=80",
    ],
    sizes: ["S", "M", "L", "XL"],
    colors: [
      { name: "Grey", hex: "#808080" },
      { name: "Light Grey", hex: "#B0B0B0" },
    ],
    stock: 14,
    isNew: true,
    viewsCount: 156,
  },
  {
    name: { ru: "Комплект Blazer + Chinos", tj: "Комплекти Blazer + Chinos" },
    description: {
      ru: "Smart-casual комплект: структурный блейзер и чиносы из хлопкового twill. Стиль без формальности.",
      tj: "Комплекти smart-casual: blazer ва chinos аз twill-и пахта.",
    },
    category: "sets",
    brand: "Golib",
    price: 1990,
    oldPrice: 2490,
    images: [
      "https://images.unsplash.com/photo-1507679799987-c73779514523?w=800&q=80",
      "https://images.unsplash.com/photo-1490367532201-b9bc1dc483f6?w=800&q=80",
    ],
    sizes: ["S", "M", "L", "XL"],
    colors: [
      { name: "Beige", hex: "#C8B89A" },
      { name: "Olive", hex: "#556B2F" },
    ],
    stock: 9,
    isPopular: true,
    viewsCount: 189,
    boughtToday: 5,
  },
  {
    name: { ru: "Костюм Wedding Ivory", tj: "Костюми Wedding Ivory" },
    description: {
      ru: "Элегантный светлый костюм для торжеств. Кремовый оттенок, атласный галстук в комплекте.",
      tj: "Костюми зебои равшан барои тӯҳфаҳо. Ранги крем ва галстук дар комплект.",
    },
    category: "sets",
    brand: "Golib",
    price: 3190,
    images: [
      "https://images.unsplash.com/photo-1593032451550-926893e4e4e8?w=800&q=80",
      "https://images.unsplash.com/photo-1515377901643-8667fd8c9a70?w=800&q=80",
    ],
    sizes: ["S", "M", "L", "XL"],
    colors: [{ name: "Ivory", hex: "#FFFFF0" }],
    stock: 5,
    isNew: true,
    viewsCount: 97,
  },
  {
    name: { ru: "Тройка Classic Charcoal", tj: "Сеҷа Classic Charcoal" },
    description: {
      ru: "Костюм-тройка с жилетом. Глубокий угольный цвет, премиальная шерсть с добавлением кашемира.",
      tj: "Костюми сеҷа бо жилет. Ранги зғол ва пашми премиум бо кашmir.",
    },
    category: "sets",
    brand: "Golib",
    price: 3490,
    oldPrice: 3990,
    images: [
      "https://images.unsplash.com/photo-1618886614638-80e3c103d31a?w=800&q=80",
      "https://images.unsplash.com/photo-1626379953822-665e0e9b8b8e?w=800&q=80",
    ],
    sizes: ["M", "L", "XL", "XXL"],
    colors: [{ name: "Charcoal", hex: "#36454F" }],
    stock: 4,
    isPopular: true,
    viewsCount: 124,
    boughtToday: 3,
  },
  {
    name: { ru: "Костюм Linen Summer", tj: "Костюми Linen Summer" },
    description: {
      ru: "Лёгкий льняной костюм для жаркого климата. Дышит, не мнётся, сохраняет форму.",
      tj: "Костюми сабук аз катон барои иqlim гарм. Нафас мегирад ва шаклро нигоҳ медорад.",
    },
    category: "sets",
    brand: "Golib",
    price: 2190,
    images: [
      "https://images.unsplash.com/photo-1591047139829-d91aecb6caea?w=800&q=80",
      "https://images.unsplash.com/photo-1503341451603-1112a804d5d6?w=800&q=80",
    ],
    sizes: ["S", "M", "L", "XL"],
    colors: [
      { name: "Sand", hex: "#C2B280" },
      { name: "Sky Blue", hex: "#87CEEB" },
    ],
    stock: 12,
    isNew: true,
    viewsCount: 88,
  },
  {
    name: { ru: "Костюм Velvet Evening", tj: "Кostюми Velvet Evening" },
    description: {
      ru: "Бархатный костюм для вечерних выходов. Глубокий изумрудный оттенок, атласные лацканы.",
      tj: "Костюми бархатӣ барои шабҳои тарафдор. Ранги зумуррад ва лацканҳои атласӣ.",
    },
    category: "sets",
    brand: "Golib",
    price: 3790,
    images: [
      "https://images.unsplash.com/photo-1539533018447-63fcce2678e3?w=800&q=80",
      "https://images.unsplash.com/photo-1509631179647-0177331693ae?w=800&q=80",
    ],
    sizes: ["S", "M", "L"],
    colors: [
      { name: "Emerald", hex: "#046307" },
      { name: "Burgundy", hex: "#800020" },
    ],
    stock: 3,
    viewsCount: 201,
    boughtToday: 2,
  },
  {
    name: { ru: "Комплект Sport-Chic", tj: "Комплекти Sport-Chic" },
    description: {
      ru: "Спортивный пиджак и брюки из трикотажа премиум. Комфорт и стиль в одном комплекте.",
      tj: "Курта ва шим аз трикотажи премиум. Роҳат ва усул дар як комплект.",
    },
    category: "sets",
    brand: "Golib",
    price: 1790,
    oldPrice: 2190,
    images: [
      "https://images.unsplash.com/photo-1618354691373-d851c5c3a990?w=800&q=80",
      "https://images.unsplash.com/photo-1624378515194-6db764131875?w=800&q=80",
    ],
    sizes: ["S", "M", "L", "XL"],
    colors: [
      { name: "Black", hex: "#0a0a0a" },
      { name: "Navy", hex: "#1B2838" },
    ],
    stock: 16,
    isPopular: true,
    viewsCount: 167,
    boughtToday: 9,
  },
  {
    name: { ru: "Костюм Double-Breasted", tj: "Кostюми Double-Breasted" },
    description: {
      ru: "Двубортный костюм в стиле old money. Широкие лацканы, структурные плечи, роскошная посадка.",
      tj: "Костюми дубортӣ бо лацканҳои васеъ ва китфҳои сохторӣ.",
    },
    category: "sets",
    brand: "Golib",
    price: 3290,
    images: [
      "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=800&q=80",
      "https://images.unsplash.com/photo-1618886614638-80e3c103d31a?w=800&q=80",
    ],
    sizes: ["M", "L", "XL"],
    colors: [{ name: "Midnight", hex: "#191970" }],
    stock: 6,
    isNew: true,
    isPopular: true,
    viewsCount: 143,
    boughtToday: 4,
  },
];

const tShirts: ProductSeed[] = [
  {
    name: { ru: "Футболка Essential White", tj: "Футболкаи Essential White" },
    description: {
      ru: "Базовая футболка из органического хлопка 220 gsm. Плотная, не просвечивает, идеальный крой.",
      tj: "Футболкаи асосӣ аз пахтаи органикӣ 220 gsm. Замин ва бури комил.",
    },
    category: "t-shirts",
    brand: "Golib",
    price: 290,
    images: [
      "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=800&q=80",
      "https://images.unsplash.com/photo-1583743814966-6a8c0709b910?w=800&q=80",
    ],
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    colors: [
      { name: "White", hex: "#FFFFFF" },
      { name: "Black", hex: "#0a0a0a" },
    ],
    stock: 48,
    isNew: true,
    isPopular: true,
    viewsCount: 412,
    boughtToday: 18,
  },
  {
    name: { ru: "Футболка Oversized Black", tj: "Футболкаи Oversized Black" },
    description: {
      ru: "Oversized футболка свободного кроя. Мягкий хлопок, dropped shoulders, streetwear эстетика.",
      tj: "Футболкаи oversized бо бури озод. Пахтаи нарм ва усули кӯчагӣ.",
    },
    category: "t-shirts",
    brand: "Golib",
    price: 390,
    images: [
      "https://images.unsplash.com/photo-1576566588028-4147f3842f27?w=800&q=80",
      "https://images.unsplash.com/photo-1622445275463-606c4e0724fb?w=800&q=80",
    ],
    sizes: ["S", "M", "L", "XL"],
    colors: [
      { name: "Black", hex: "#0a0a0a" },
      { name: "Stone", hex: "#928E85" },
    ],
    stock: 32,
    isPopular: true,
    viewsCount: 287,
    boughtToday: 11,
  },
  {
    name: { ru: "Поло Premium Piqué", tj: "Поло Premium Piqué" },
    description: {
      ru: "Поло из пике премиум-класса. Воротник держит форму, пуговицы из перламутра.",
      tj: "Поло аз пикеи премиум. Яқас шаклро нигоҳ медорад.",
    },
    category: "t-shirts",
    brand: "Golib",
    price: 490,
    oldPrice: 590,
    images: [
      "https://images.unsplash.com/photo-1586363104862-3a5e2ab60d99?w=800&q=80",
      "https://images.unsplash.com/photo-1625910654518-559c68471b66?w=800&q=80",
    ],
    sizes: ["S", "M", "L", "XL"],
    colors: [
      { name: "Navy", hex: "#1B2838" },
      { name: "White", hex: "#FFFFFF" },
      { name: "Forest", hex: "#228B22" },
    ],
    stock: 22,
    isNew: true,
    viewsCount: 134,
  },
  {
    name: { ru: "Футболка Graphic Minimal", tj: "Футболкаи Graphic Minimal" },
    description: {
      ru: "Минималистичный принт Golib на груди. Печать не выцветает после 50+ стирок.",
      tj: "Чопи минималистии Golib. Набас пас аз 50+ шустушӯӣ.",
    },
    category: "t-shirts",
    brand: "Golib",
    price: 350,
    images: [
      "https://images.unsplash.com/photo-1581655353564-d7831230a2b2?w=800&q=80",
      "https://images.unsplash.com/photo-1571946255264-0dba2755644f?w=800&q=80",
    ],
    sizes: ["S", "M", "L", "XL"],
    colors: [
      { name: "Grey", hex: "#808080" },
      { name: "Black", hex: "#0a0a0a" },
    ],
    stock: 28,
    viewsCount: 98,
    boughtToday: 6,
  },
  {
    name: { ru: "Henley Long Sleeve", tj: "Henley Long Sleeve" },
    description: {
      ru: "Лонгслив с планкой на пуговицах. Джерси из combed cotton, приятный к телу.",
      tj: "Лонгслив бо тугмаҳо. Джерси аз пахтаи combed.",
    },
    category: "t-shirts",
    brand: "Golib",
    price: 420,
    images: [
      "https://images.unsplash.com/photo-1618354691373-d851c5c3a990?w=800&q=80",
      "https://images.unsplash.com/photo-1622445275463-606c4e0724fb?w=800&q=80",
    ],
    sizes: ["S", "M", "L", "XL"],
    colors: [
      { name: "Olive", hex: "#556B2F" },
      { name: "Charcoal", hex: "#36454F" },
    ],
    stock: 19,
    isNew: true,
    viewsCount: 76,
  },
  {
    name: { ru: "V-Neck Merino", tj: "V-Neck Merino" },
    description: {
      ru: "Тонкий свитер из мериносовой шерсти. V-образный вырез, идеален под пиджак.",
      tj: "Свитер аз пашми merino. Бури V ва мувофиқ зери курта.",
    },
    category: "t-shirts",
    brand: "Golib",
    price: 690,
    oldPrice: 890,
    images: [
      "https://images.unsplash.com/photo-1434389677669-e08b4cac3105?w=800&q=80",
      "https://images.unsplash.com/photo-1620799140408-edc089dcb070?w=800&q=80",
    ],
    sizes: ["S", "M", "L", "XL"],
    colors: [
      { name: "Camel", hex: "#C19A6B" },
      { name: "Navy", hex: "#1B2838" },
    ],
    stock: 15,
    isPopular: true,
    viewsCount: 112,
    boughtToday: 4,
  },
  {
    name: { ru: "Футболка Striped Breton", tj: "Футболкаи Striped Breton" },
    description: {
      ru: "Морская полоска в премиальном исполнении. Французский стиль, плотный хлопок.",
      tj: "Хатҳои баҳрӣ бо усули фаронсавӣ. Пахтаи замин.",
    },
    category: "t-shirts",
    brand: "Golib",
    price: 380,
    images: [
      "https://images.unsplash.com/photo-1503341504253-dff4815485f1?w=800&q=80",
      "https://images.unsplash.com/photo-1583743814966-6a8c0709b910?w=800&q=80",
    ],
    sizes: ["S", "M", "L", "XL"],
    colors: [{ name: "Navy/White", hex: "#1B2838" }],
    stock: 24,
    viewsCount: 89,
  },
  {
    name: { ru: "Relaxed Fit Sage", tj: "Relaxed Fit Sage" },
    description: {
      ru: "Расслабленный крой, приглушённый sage green. Мягкая ткань, идеальна для выходных.",
      tj: "Бури ором, ранги sage green. Матои нарм барои истироҳат.",
    },
    category: "t-shirts",
    brand: "Golib",
    price: 340,
    images: [
      "https://images.unsplash.com/photo-1620012253295-c15cc3e65df4?w=800&q=80",
      "https://images.unsplash.com/photo-1576566588028-4147f3842f27?w=800&q=80",
    ],
    sizes: ["S", "M", "L", "XL"],
    colors: [{ name: "Sage", hex: "#9DC183" }],
    stock: 21,
    isNew: true,
    viewsCount: 67,
  },
  {
    name: { ru: "Performance Dry-Fit", tj: "Performance Dry-Fit" },
    description: {
      ru: "Спортивная футболка с технологией moisture-wicking. Быстро сохнет, антибактериальная обработка.",
      tj: "Футболкаи варзишӣ бо технологияи moisture-wicking.",
    },
    category: "t-shirts",
    brand: "Golib",
    price: 450,
    images: [
      "https://images.unsplash.com/photo-1618354691373-d851c5c3a990?w=800&q=80",
      "https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?w=800&q=80",
    ],
    sizes: ["S", "M", "L", "XL"],
    colors: [
      { name: "Black", hex: "#0a0a0a" },
      { name: "Electric Blue", hex: "#0066CC" },
    ],
    stock: 35,
    isPopular: true,
    viewsCount: 178,
    boughtToday: 8,
  },
  {
    name: { ru: "Crew Neck Cashmere Blend", tj: "Crew Neck Cashmere Blend" },
    description: {
      ru: "Футболка из смеси хлопка и кашемира. Невероятно мягкая, люксовое ощущение на коже.",
      tj: "Футболка аз омезиши пахта ва кашmir. Нарм ва люks.",
    },
    category: "t-shirts",
    brand: "Golib",
    price: 590,
    oldPrice: 790,
    images: [
      "https://images.unsplash.com/photo-1620799140408-edc089dcb070?w=800&q=80",
      "https://images.unsplash.com/photo-1434389677669-e08b4cac3105?w=800&q=80",
    ],
    sizes: ["S", "M", "L", "XL"],
    colors: [
      { name: "Cream", hex: "#FFFDD0" },
      { name: "Black", hex: "#0a0a0a" },
    ],
    stock: 12,
    isNew: true,
    isPopular: true,
    viewsCount: 145,
    boughtToday: 5,
  },
];

const shirts: ProductSeed[] = [
  {
    name: { ru: "Рубашка Oxford Classic", tj: "Куртаи Oxford Classic" },
    description: {
      ru: "Классическая Oxford рубашка с button-down воротником. Универсальная база гардероба.",
      tj: "Куртаи классикии Oxford бо яқаси button-down.",
    },
    category: "shirts",
    brand: "Golib",
    price: 590,
    oldPrice: 790,
    images: [
      "https://images.unsplash.com/photo-1596755094514-f87e34085b2c?w=800&q=80",
      "https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?w=800&q=80",
    ],
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: [
      { name: "White", hex: "#FFFFFF" },
      { name: "Light Blue", hex: "#ADD8E6" },
    ],
    stock: 26,
    isPopular: true,
    viewsCount: 234,
    boughtToday: 9,
  },
  {
    name: { ru: "Рубашка Linen Resort", tj: "Куртаи Linen Resort" },
    description: {
      ru: "Льняная рубашка для отдыха. Лёгкая, дышащая, слегка текстурная поверхность.",
      tj: "Куртаи катонӣ барои истироҳат. Сабук ва нафасгир.",
    },
    category: "shirts",
    brand: "Golib",
    price: 690,
    images: [
      "https://images.unsplash.com/photo-1598033129183-c507f312091f?w=800&q=80",
      "https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?w=800&q=80",
    ],
    sizes: ["S", "M", "L", "XL"],
    colors: [
      { name: "White", hex: "#FFFFFF" },
      { name: "Beige", hex: "#F5F5DC" },
    ],
    stock: 18,
    isNew: true,
    viewsCount: 102,
  },
  {
    name: { ru: "Рубашка Denim Western", tj: "Куртаи Denim Western" },
    description: {
      ru: "Джинсовая рубашка в western стиле. Классический крой, качественный деним 12 oz.",
      tj: "Куртаи denim бо усули western. Дenim 12 oz.",
    },
    category: "shirts",
    brand: "Golib",
    price: 790,
    oldPrice: 990,
    images: [
      "https://images.unsplash.com/photo-1564257631407-4deb1f99d992?w=800&q=80",
      "https://images.unsplash.com/photo-1598033129183-c507f312091f?w=800&q=80",
    ],
    sizes: ["S", "M", "L", "XL"],
    colors: [{ name: "Indigo", hex: "#3F51B5" }],
    stock: 14,
    isPopular: true,
    viewsCount: 156,
    boughtToday: 6,
  },
  {
    name: { ru: "Рубашка Silk Evening", tj: "Куртаи Silk Evening" },
    description: {
      ru: "Шёлковая рубашка для вечерних мероприятий. Благородный блеск, идеальная посадка.",
      tj: "Куртаи абрӣ барои шабҳои тарафдор. Дурахш ва бури комил.",
    },
    category: "shirts",
    brand: "Golib",
    price: 1290,
    images: [
      "https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?w=800&q=80",
      "https://images.unsplash.com/photo-1596755094514-f87e34085b2c?w=800&q=80",
    ],
    sizes: ["S", "M", "L", "XL"],
    colors: [
      { name: "Black", hex: "#0a0a0a" },
      { name: "Champagne", hex: "#F7E7CE" },
    ],
    stock: 7,
    isNew: true,
    viewsCount: 88,
  },
  {
    name: { ru: "Рубашка Flannel Check", tj: "Куртаи Flannel Check" },
    description: {
      ru: "Фланелевая рубашка в клетку. Мягкая, тёплая, идеальна для прохладной погоды.",
      tj: "Куртаи flannel бо хати чоркунa. Нарм ва гарм.",
    },
    category: "shirts",
    brand: "Golib",
    price: 650,
    images: [
      "https://images.unsplash.com/photo-1598033129183-c507f312091f?w=800&q=80",
      "https://images.unsplash.com/photo-1564257631407-4deb1f99d992?w=800&q=80",
    ],
    sizes: ["S", "M", "L", "XL"],
    colors: [
      { name: "Red Check", hex: "#8B0000" },
      { name: "Green Check", hex: "#228B22" },
    ],
    stock: 20,
    viewsCount: 94,
  },
  {
    name: { ru: "Рубашка Mandarin Collar", tj: "Куртаи Mandarin Collar" },
    description: {
      ru: "Рубашка с воротником-стойкой. Минималистичный азиатский акцент, хлопок poplin.",
      tj: "Курта бо яқаси mandarin. Акценти минималистии Осиё.",
    },
    category: "shirts",
    brand: "Golib",
    price: 620,
    images: [
      "https://images.unsplash.com/photo-1596755094514-f87e34085b2c?w=800&q=80",
      "https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?w=800&q=80",
    ],
    sizes: ["S", "M", "L", "XL"],
    colors: [
      { name: "White", hex: "#FFFFFF" },
      { name: "Black", hex: "#0a0a0a" },
    ],
    stock: 16,
    isNew: true,
    viewsCount: 71,
  },
  {
    name: { ru: "Рубашка Oxford Button-Down Blue", tj: "Куртаи Oxford Blue" },
    description: {
      ru: "Голубая Oxford — must-have для smart-casual. Контрастная строчка, манжеты на две пуговицы.",
      tj: "Oxford кabud — зарurӣ барои smart-casual.",
    },
    category: "shirts",
    brand: "Golib",
    price: 560,
    images: [
      "https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?w=800&q=80",
      "https://images.unsplash.com/photo-1596755094514-f87e34085b2c?w=800&q=80",
    ],
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: [{ name: "Sky Blue", hex: "#87CEEB" }],
    stock: 29,
    isPopular: true,
    viewsCount: 187,
    boughtToday: 7,
  },
  {
    name: { ru: "Рубашка Oversized Poplin", tj: "Куртаи Oversized Poplin" },
    description: {
      ru: "Свободная рубашка из poplin. Современный силуэт, носится заправленной или навыпуск.",
      tj: "Куртаи озод аз poplin. Силуети муосир.",
    },
    category: "shirts",
    brand: "Golib",
    price: 580,
    images: [
      "https://images.unsplash.com/photo-1598033129183-c507f312091f?w=800&q=80",
      "https://images.unsplash.com/photo-1564257631407-4deb1f99d992?w=800&q=80",
    ],
    sizes: ["S", "M", "L", "XL"],
    colors: [
      { name: "Ecru", hex: "#C2B280" },
      { name: "Black", hex: "#0a0a0a" },
    ],
    stock: 17,
    viewsCount: 83,
  },
  {
    name: { ru: "Рубашка Cuban Short Sleeve", tj: "Куртаи Cuban Short Sleeve" },
    description: {
      ru: "Кубинская рубашка с коротким рукавом. Яркий принт, лёгкая viscose, отпускной стиль.",
      tj: "Куртаи cuban бо дасти кӯтоҳ. Чопи равshan ва viscose.",
    },
    category: "shirts",
    brand: "Golib",
    price: 540,
    oldPrice: 690,
    images: [
      "https://images.unsplash.com/photo-1596755094514-f87e34085b2c?w=800&q=80",
      "https://images.unsplash.com/photo-1598033129183-c507f312091f?w=800&q=80",
    ],
    sizes: ["S", "M", "L", "XL"],
    colors: [
      { name: "Tropical", hex: "#FF6B35" },
      { name: "Palm Green", hex: "#2E8B57" },
    ],
    stock: 22,
    isNew: true,
    isPopular: true,
    viewsCount: 129,
    boughtToday: 5,
  },
  {
    name: { ru: "Рубашка Satin Dress", tj: "Куртаи Satin Dress" },
    description: {
      ru: "Праздничная атласная рубашка. Гладкая поверхность, french cuffs, элегантный блеск.",
      tj: "Куртаи атласӣ барои ид. Сathи ҳамвор ва дuraхsh.",
    },
    category: "shirts",
    brand: "Golib",
    price: 890,
    images: [
      "https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?w=800&q=80",
      "https://images.unsplash.com/photo-1596755094514-f87e34085b2c?w=800&q=80",
    ],
    sizes: ["S", "M", "L", "XL"],
    colors: [
      { name: "White", hex: "#FFFFFF" },
      { name: "Midnight", hex: "#191970" },
    ],
    stock: 10,
    viewsCount: 76,
  },
];

const pants: ProductSeed[] = [
  {
    name: { ru: "Брюки Tailored Fit", tj: "Шимҳои Tailored Fit" },
    description: {
      ru: "Классические брюки tailored fit. Шерсть с эластаном, стрелки, идеальная длина.",
      tj: "Шимҳои классикии tailored fit. Пашм бо elastan.",
    },
    category: "pants",
    brand: "Golib",
    price: 890,
    oldPrice: 1090,
    images: [
      "https://images.unsplash.com/photo-1473966968600-fa801b869a1a?w=800&q=80",
      "https://images.unsplash.com/photo-1624378515194-6db764131875?w=800&q=80",
    ],
    sizes: ["30", "32", "34", "36", "38"],
    colors: [
      { name: "Black", hex: "#0a0a0a" },
      { name: "Charcoal", hex: "#36454F" },
    ],
    stock: 22,
    isNew: true,
    isPopular: true,
    viewsCount: 198,
    boughtToday: 8,
  },
  {
    name: { ru: "Chino Beige Classic", tj: "Chino Beige Classic" },
    description: {
      ru: "Чиносы из хлопкового twill. Универсальный бежевый оттенок, slim fit.",
      tj: "Chinos аз twill-и пахта. Ранги беж ва slim fit.",
    },
    category: "pants",
    brand: "Golib",
    price: 690,
    images: [
      "https://images.unsplash.com/photo-1624378515194-6db764131875?w=800&q=80",
      "https://images.unsplash.com/photo-1473966968600-fa801b869a1a?w=800&q=80",
    ],
    sizes: ["30", "32", "34", "36", "38"],
    colors: [
      { name: "Beige", hex: "#F5F5DC" },
      { name: "Khaki", hex: "#C3B091" },
    ],
    stock: 28,
    isPopular: true,
    viewsCount: 167,
    boughtToday: 6,
  },
  {
    name: { ru: "Брюки Wool Trousers Navy", tj: "Шимҳои Wool Navy" },
    description: {
      ru: "Шерстяные брюки для офиса. Тёмно-синие, без складок, премиальная драпировка.",
      tj: "Шимҳои пашмӣ барои офис. Кabudи торik.",
    },
    category: "pants",
    brand: "Golib",
    price: 990,
    oldPrice: 1190,
    images: [
      "https://images.unsplash.com/photo-1473966968600-fa801b869a1a?w=800&q=80",
      "https://images.unsplash.com/photo-1624378515194-6db764131875?w=800&q=80",
    ],
    sizes: ["30", "32", "34", "36", "38"],
    colors: [{ name: "Navy", hex: "#1B2838" }],
    stock: 15,
    viewsCount: 112,
  },
  {
    name: { ru: "Брюки Cargo Utility", tj: "Шимҳои Cargo Utility" },
    description: {
      ru: "Карго с функциональными карманами. Прочная ткань, relaxed fit, urban utility стиль.",
      tj: "Cargo бо ҷайби функсional. Матои мустахkam.",
    },
    category: "pants",
    brand: "Golib",
    price: 790,
    images: [
      "https://images.unsplash.com/photo-1624378515194-6db764131875?w=800&q=80",
      "https://images.unsplash.com/photo-1473966968600-fa801b869a1a?w=800&q=80",
    ],
    sizes: ["30", "32", "34", "36", "38", "40"],
    colors: [
      { name: "Olive", hex: "#556B2F" },
      { name: "Black", hex: "#0a0a0a" },
    ],
    stock: 19,
    isNew: true,
    viewsCount: 134,
    boughtToday: 4,
  },
  {
    name: { ru: "Брюки Pleated Wide Leg", tj: "Шимҳои Pleated Wide Leg" },
    description: {
      ru: "Широкие брюки со складками. Трендовый силуэт, высокая посадка, flowy движение.",
      tj: "Шимҳои васеъ бо чакmak. Силuetи муосир.",
    },
    category: "pants",
    brand: "Golib",
    price: 850,
    images: [
      "https://images.unsplash.com/photo-1473966968600-fa801b869a1a?w=800&q=80",
      "https://images.unsplash.com/photo-1624378515194-6db764131875?w=800&q=80",
    ],
    sizes: ["30", "32", "34", "36", "38"],
    colors: [
      { name: "Cream", hex: "#FFFDD0" },
      { name: "Black", hex: "#0a0a0a" },
    ],
    stock: 12,
    isPopular: true,
    viewsCount: 98,
  },
  {
    name: { ru: "Jogger Premium", tj: "Jogger Premium" },
    description: {
      ru: "Премиальные джоггеры из смеси хлопка и модала. Мягкие, с манжетами, smart-casual.",
      tj: "Jogger аз омезиши пахта ва modal. Нарм ва smart-casual.",
    },
    category: "pants",
    brand: "Golib",
    price: 590,
    images: [
      "https://images.unsplash.com/photo-1624378515194-6db764131875?w=800&q=80",
      "https://images.unsplash.com/photo-1473966968600-fa801b869a1a?w=800&q=80",
    ],
    sizes: ["S", "M", "L", "XL"],
    colors: [
      { name: "Grey", hex: "#808080" },
      { name: "Black", hex: "#0a0a0a" },
    ],
    stock: 31,
    isNew: true,
    isPopular: true,
    viewsCount: 245,
    boughtToday: 12,
  },
  {
    name: { ru: "Брюки Corduroy Brown", tj: "Шимҳои Corduroy Brown" },
    description: {
      ru: "Вельветовые брюки шириной wale. Тёплый коричневый, осенне-зимний must-have.",
      tj: "Шимҳои corduroy. Qahvehii garm барои тирамоҳ.",
    },
    category: "pants",
    brand: "Golib",
    price: 750,
    oldPrice: 890,
    images: [
      "https://images.unsplash.com/photo-1473966968600-fa801b869a1a?w=800&q=80",
      "https://images.unsplash.com/photo-1624378515194-6db764131875?w=800&q=80",
    ],
    sizes: ["30", "32", "34", "36", "38"],
    colors: [{ name: "Brown", hex: "#8B4513" }],
    stock: 14,
    viewsCount: 87,
  },
  {
    name: { ru: "Брюки Linen Drawstring", tj: "Шимҳои Linen Drawstring" },
    description: {
      ru: "Льняные брюки на резинке. Максимальный комфорт, летний стиль, свободный крой.",
      tj: "Шимҳои катонӣ бо резинка. Роҳати максималӣ.",
    },
    category: "pants",
    brand: "Golib",
    price: 620,
    images: [
      "https://images.unsplash.com/photo-1624378515194-6db764131875?w=800&q=80",
      "https://images.unsplash.com/photo-1473966968600-fa801b869a1a?w=800&q=80",
    ],
    sizes: ["S", "M", "L", "XL"],
    colors: [
      { name: "Natural", hex: "#E8DCC4" },
      { name: "White", hex: "#FFFFFF" },
    ],
    stock: 20,
    isNew: true,
    viewsCount: 72,
  },
  {
    name: { ru: "Брюки Slim Tuxedo", tj: "Шимҳои Slim Tuxedo" },
    description: {
      ru: "Брюки под смoking. Атласная лента по бокам, slim fit, без задних карманов.",
      tj: "Шим барои smoking. Лenta атlasӣ ва slim fit.",
    },
    category: "pants",
    brand: "Golib",
    price: 1090,
    images: [
      "https://images.unsplash.com/photo-1473966968600-fa801b869a1a?w=800&q=80",
      "https://images.unsplash.com/photo-1624378515194-6db764131875?w=800&q=80",
    ],
    sizes: ["30", "32", "34", "36", "38"],
    colors: [{ name: "Black", hex: "#0a0a0a" }],
    stock: 8,
    viewsCount: 54,
  },
  {
    name: { ru: "Брюки Tech Stretch", tj: "Шимҳои Tech Stretch" },
    description: {
      ru: "Брюки с 4-way stretch. Для активного дня: офис, поездки, долгие прогулки.",
      tj: "Шим бо 4-way stretch. Барои рӯзи фаъол.",
    },
    category: "pants",
    brand: "Golib",
    price: 820,
    images: [
      "https://images.unsplash.com/photo-1624378515194-6db764131875?w=800&q=80",
      "https://images.unsplash.com/photo-1473966968600-fa801b869a1a?w=800&q=80",
    ],
    sizes: ["30", "32", "34", "36", "38", "40"],
    colors: [
      { name: "Charcoal", hex: "#36454F" },
      { name: "Navy", hex: "#1B2838" },
    ],
    stock: 24,
    isPopular: true,
    viewsCount: 156,
    boughtToday: 5,
  },
];

const shoes: ProductSeed[] = [
  {
    name: { ru: "Кроссовки Urban Runner", tj: "Кроссовкаҳои Urban Runner" },
    description: {
      ru: "Лёгкие кроссовки для города. Пена EVA, дышащий mesh, подошва с амортизацией.",
      tj: "Кроссовкаҳои сабук барои шаҳр. EVA ва mesh.",
    },
    category: "shoes",
    brand: "Golib",
    price: 1290,
    oldPrice: 1590,
    images: [
      "https://images.unsplash.com/photo-1549298916-b41d501d3772?w=800&q=80",
      "https://images.unsplash.com/photo-1606107557195-0e29a4b5b4aa?w=800&q=80",
    ],
    sizes: ["40", "41", "42", "43", "44", "45"],
    colors: [
      { name: "White", hex: "#FFFFFF" },
      { name: "Green", hex: "#00A531" },
    ],
    stock: 18,
    isPopular: true,
    viewsCount: 389,
    boughtToday: 15,
  },
  {
    name: { ru: "Oxford Leather Brown", tj: "Oxford Leather Brown" },
    description: {
      ru: "Классические Oxford из натуральной кожи. Goodyear welt, кожаная подошва.",
      tj: "Oxford аз чарми табиӣ. Goodyear welt.",
    },
    category: "shoes",
    brand: "Golib",
    price: 1890,
    oldPrice: 2290,
    images: [
      "https://images.unsplash.com/photo-1614252238916-18c04c494748?w=800&q=80",
      "https://images.unsplash.com/photo-1533867612531-8a2f2a3a2f2a?w=800&q=80",
    ],
    sizes: ["40", "41", "42", "43", "44"],
    colors: [{ name: "Brown", hex: "#8B4513" }],
    stock: 9,
    isNew: true,
    isPopular: true,
    viewsCount: 178,
    boughtToday: 4,
  },
  {
    name: { ru: "Chelsea Boot Black", tj: "Chelsea Boot Black" },
    description: {
      ru: "Челси из гладкой кожи. Эластичные вставки, минималистичный силуэт, всесезонные.",
      tj: "Chelsea аз чарми ҳамвор. Силuetи минималистӣ.",
    },
    category: "shoes",
    brand: "Golib",
    price: 2190,
    images: [
      "https://images.unsplash.com/photo-1608256246200-53e635b5b65f?w=800&q=80",
      "https://images.unsplash.com/photo-1638247025967-f402042a6f2d?w=800&q=80",
    ],
    sizes: ["40", "41", "42", "43", "44", "45"],
    colors: [
      { name: "Black", hex: "#0a0a0a" },
      { name: "Tan", hex: "#D2B48C" },
    ],
    stock: 11,
    isPopular: true,
    viewsCount: 234,
    boughtToday: 6,
  },
  {
    name: { ru: "Sneaker Minimal White", tj: "Sneaker Minimal White" },
    description: {
      ru: "Минималистичные белые кеды. Кожа premium, clean lines, capsule wardrobe essential.",
      tj: "Кедҳои сафеди минималистӣ. Чарми премиум.",
    },
    category: "shoes",
    brand: "Golib",
    price: 1490,
    images: [
      "https://images.unsplash.com/photo-1606107557195-0e29a4b5b4aa?w=800&q=80",
      "https://images.unsplash.com/photo-1549298916-b41d501d3772?w=800&q=80",
    ],
    sizes: ["40", "41", "42", "43", "44", "45"],
    colors: [{ name: "White", hex: "#FFFFFF" }],
    stock: 22,
    isNew: true,
    viewsCount: 267,
    boughtToday: 9,
  },
  {
    name: { ru: "Derby Classic Black", tj: "Derby Classic Black" },
    description: {
      ru: "Классические Derby с открытой шнуровкой. Полированная кожа, формальный стиль.",
      tj: "Derby классикӣ бо пӯшидаи кушода.",
    },
    category: "shoes",
    brand: "Golib",
    price: 1790,
    oldPrice: 2090,
    images: [
      "https://images.unsplash.com/photo-1614252238916-18c04c494748?w=800&q=80",
      "https://images.unsplash.com/photo-1533867612531-8a2f2a3a2f2a?w=800&q=80",
    ],
    sizes: ["40", "41", "42", "43", "44"],
    colors: [{ name: "Black", hex: "#0a0a0a" }],
    stock: 10,
    viewsCount: 145,
  },
  {
    name: { ru: "Loafers Suede Tan", tj: "Loafers Suede Tan" },
    description: {
      ru: "Лоферы из замши. Без шнурков, penny slot, итальянский крой.",
      tj: "Loafers аз замша. Бидун пӯшида, бури итолиё.",
    },
    category: "shoes",
    brand: "Golib",
    price: 1590,
    images: [
      "https://images.unsplash.com/photo-1533867612531-8a2f2a3a2f2a?w=800&q=80",
      "https://images.unsplash.com/photo-1614252238916-18c04c494748?w=800&q=80",
    ],
    sizes: ["40", "41", "42", "43", "44"],
    colors: [
      { name: "Tan", hex: "#D2B48C" },
      { name: "Navy", hex: "#1B2838" },
    ],
    stock: 13,
    isNew: true,
    isPopular: true,
    viewsCount: 198,
    boughtToday: 5,
  },
  {
    name: { ru: "High-Top Street", tj: "High-Top Street" },
    description: {
      ru: "Хайтопы в streetwear стиле. Кожа и canvas, контрастная подошва, bold look.",
      tj: "High-top бо усули streetwear. Чarm ва canvas.",
    },
    category: "shoes",
    brand: "Golib",
    price: 1390,
    images: [
      "https://images.unsplash.com/photo-1608231387042-66d1773070a5?w=800&q=80",
      "https://images.unsplash.com/photo-1549298916-b41d501d3772?w=800&q=80",
    ],
    sizes: ["40", "41", "42", "43", "44", "45"],
    colors: [
      { name: "Black/White", hex: "#0a0a0a" },
      { name: "Red", hex: "#DC143C" },
    ],
    stock: 16,
    viewsCount: 167,
    boughtToday: 7,
  },
  {
    name: { ru: "Monk Strap Double", tj: "Monk Strap Double" },
    description: {
      ru: "Двойные монки из кожи box calf. Элегантная альтернатива Oxford, sartorial стиль.",
      tj: "Monk strap дuбл аз чarmи box calf.",
    },
    category: "shoes",
    brand: "Golib",
    price: 1990,
    images: [
      "https://images.unsplash.com/photo-1614252238916-18c04c494748?w=800&q=80",
      "https://images.unsplash.com/photo-1638247025967-f402042a6f2d?w=800&q=80",
    ],
    sizes: ["40", "41", "42", "43", "44"],
    colors: [{ name: "Burgundy", hex: "#800020" }],
    stock: 6,
    isNew: true,
    viewsCount: 89,
  },
  {
    name: { ru: "Running Pro", tj: "Running Pro" },
    description: {
      ru: "Беговые кроссовки с карбоновой пластиной. Максимальный возврат энергии, pro level.",
      tj: "Кrosсовкаи давидan бо пластинаи карbon.",
    },
    category: "shoes",
    brand: "Golib",
    price: 1690,
    oldPrice: 1990,
    images: [
      "https://images.unsplash.com/photo-1606107557195-0e29a4b5b4aa?w=800&q=80",
      "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=800&q=80",
    ],
    sizes: ["40", "41", "42", "43", "44", "45"],
    colors: [
      { name: "Neon", hex: "#39FF14" },
      { name: "Black", hex: "#0a0a0a" },
    ],
    stock: 20,
    isPopular: true,
    viewsCount: 312,
    boughtToday: 11,
  },
  {
    name: { ru: "Desert Boot Sand", tj: "Desert Boot Sand" },
    description: {
      ru: "Desert boots из замши. Crepe подошва, Clarks-inspired, timeless classic.",
      tj: "Desert boot аз замша. Crepe ва класика.",
    },
    category: "shoes",
    brand: "Golib",
    price: 1290,
    images: [
      "https://images.unsplash.com/photo-1638247025967-f402042a6f2d?w=800&q=80",
      "https://images.unsplash.com/photo-1608256246200-53e635b5b65f?w=800&q=80",
    ],
    sizes: ["40", "41", "42", "43", "44"],
    colors: [{ name: "Sand", hex: "#C2B280" }],
    stock: 14,
    viewsCount: 124,
  },
];

const accessories: ProductSeed[] = [
  {
    name: { ru: "Сумка Leather Mini", tj: "Сумкаи Leather Mini" },
    description: {
      ru: "Мини-сумка из натуральной кожи. Crossbody, регулируемый ремень, внутренний карман.",
      tj: "Сумкаи mini аз чарми табиӣ. Crossbody.",
    },
    category: "accessories",
    brand: "Golib",
    price: 790,
    oldPrice: 990,
    images: [
      "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=800&q=80",
      "https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=800&q=80",
    ],
    sizes: ["One Size"],
    colors: [
      { name: "Brown", hex: "#8B4513" },
      { name: "Black", hex: "#0a0a0a" },
    ],
    stock: 15,
    isPopular: true,
    viewsCount: 156,
    boughtToday: 5,
  },
  {
    name: { ru: "Ремень Full Grain", tj: "Кamar Full Grain" },
    description: {
      ru: "Ремень из цельнозернистой кожи. Латунная пряжка, ручная прошивка, 35 мм.",
      tj: "Кamar аз чarmи full grain. Гhalabaи mis.",
    },
    category: "accessories",
    brand: "Golib",
    price: 390,
    images: [
      "https://images.unsplash.com/photo-1624227732930-1c8a28058103?w=800&q=80",
      "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=800&q=80",
    ],
    sizes: ["90", "95", "100", "105", "110"],
    colors: [
      { name: "Brown", hex: "#8B4513" },
      { name: "Black", hex: "#0a0a0a" },
    ],
    stock: 32,
    isNew: true,
    viewsCount: 98,
  },
  {
    name: { ru: "Кошелёк Slim Bifold", tj: "Ҳамyon Slim Bifold" },
    description: {
      ru: "Тонкий bifold кошелёк. RFID-защита, 6 слотов для карт, минимальная толщина.",
      tj: "Ҳamyonи slim bifold. Ҳimoyaи RFID.",
    },
    category: "accessories",
    brand: "Golib",
    price: 290,
    images: [
      "https://images.unsplash.com/photo-1627123424574-10a129927ad8?w=800&q=80",
      "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=800&q=80",
    ],
    sizes: ["One Size"],
    colors: [
      { name: "Black", hex: "#0a0a0a" },
      { name: "Cognac", hex: "#834333" },
    ],
    stock: 41,
    isPopular: true,
    viewsCount: 187,
    boughtToday: 8,
  },
  {
    name: { ru: "Галстук Silk Navy", tj: "Галстук Silk Navy" },
    description: {
      ru: "Шёлковый галстук ручной работы. Классическая ширина 8 см, подкладка из шерсти.",
      tj: "Галстук аз абр бо дасти. Паҳнии 8 см.",
    },
    category: "accessories",
    brand: "Golib",
    price: 490,
    images: [
      "https://images.unsplash.com/photo-1617137968427-85924c800a41?w=800&q=80",
      "https://images.unsplash.com/photo-1624227732930-1c8a28058103?w=800&q=80",
    ],
    sizes: ["One Size"],
    colors: [
      { name: "Navy", hex: "#1B2838" },
      { name: "Burgundy", hex: "#800020" },
      { name: "Emerald", hex: "#046307" },
    ],
    stock: 24,
    isNew: true,
    viewsCount: 76,
  },
  {
    name: { ru: "Запонки Silver Classic", tj: "Запonки Silver Classic" },
    description: {
      ru: "Запonки из rhodium-plated silver. Минималистичный дизайн, подарочная упаковка.",
      tj: "Зapонки аз нуқраи rhodium. Нақши минималистӣ.",
    },
    category: "accessories",
    brand: "Golib",
    price: 590,
    oldPrice: 790,
    images: [
      "https://images.unsplash.com/photo-1611591434247-44434a0d3707?w=800&q=80",
      "https://images.unsplash.com/photo-1624227732930-1c8a28058103?w=800&q=80",
    ],
    sizes: ["One Size"],
    colors: [{ name: "Silver", hex: "#C0C0C0" }],
    stock: 18,
    viewsCount: 54,
  },
  {
    name: { ru: "Ремешок Watch Leather", tj: "Тasmаи Watch Leather" },
    description: {
      ru: "Кожаный ремешок для часов 20 мм. Quick-release, итальянская кожа, универсальный.",
      tj: "Тasmаи чarm барои соat 20 мм. Quick-release.",
    },
    category: "accessories",
    brand: "Golib",
    price: 190,
    images: [
      "https://images.unsplash.com/photo-1524592094714-0f0654e20314?w=800&q=80",
      "https://images.unsplash.com/photo-1624227732930-1c8a28058103?w=800&q=80",
    ],
    sizes: ["20mm"],
    colors: [
      { name: "Brown", hex: "#8B4513" },
      { name: "Black", hex: "#0a0a0a" },
    ],
    stock: 45,
    isNew: true,
    viewsCount: 67,
  },
  {
    name: { ru: "Шарф Cashmere Blend", tj: "Шарф Cashmere Blend" },
    description: {
      ru: "Шарф из смеси кашемира и шерсти. Мягкий, тёплый, fringed края.",
      tj: "Шарф аз оmезиши кашmir ва пашm. Нарm ва garm.",
    },
    category: "accessories",
    brand: "Golib",
    price: 690,
    images: [
      "https://images.unsplash.com/photo-1520903920243-00d744a2eebf?w=800&q=80",
      "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=800&q=80",
    ],
    sizes: ["One Size"],
    colors: [
      { name: "Camel", hex: "#C19A6B" },
      { name: "Grey", hex: "#808080" },
      { name: "Navy", hex: "#1B2838" },
    ],
    stock: 19,
    isPopular: true,
    viewsCount: 112,
    boughtToday: 4,
  },
  {
    name: { ru: "Очки Aviator Gold", tj: "Айнак Aviator Gold" },
    description: {
      ru: "Аviator с золотой оправой. UV400, polarized линзы, чехол в комплекте.",
      tj: "Aviator бо чorchagai tилlo. UV400 ва polarized.",
    },
    category: "accessories",
    brand: "Golib",
    price: 890,
    oldPrice: 1090,
    images: [
      "https://images.unsplash.com/photo-1572635196233-14f3f41d6324?w=800&q=80",
      "https://images.unsplash.com/photo-1511499767150-a48a237f0083?w=800&q=80",
    ],
    sizes: ["One Size"],
    colors: [
      { name: "Gold/Green", hex: "#FFD700" },
      { name: "Silver/Blue", hex: "#C0C0C0" },
    ],
    stock: 14,
    isNew: true,
    isPopular: true,
    viewsCount: 234,
    boughtToday: 6,
  },
  {
    name: { ru: "Рюкзак City Commuter", tj: "Кӯлба City Commuter" },
    description: {
      ru: "Городской рюкзак из водоотталкивающей ткани. Отделение для ноутбука 15\", USB-порт.",
      tj: "Кӯлbaи шаҳрӣ. Ҷои laptop 15\" ва USB.",
    },
    category: "accessories",
    brand: "Golib",
    price: 990,
    images: [
      "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=800&q=80",
      "https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=800&q=80",
    ],
    sizes: ["One Size"],
    colors: [
      { name: "Black", hex: "#0a0a0a" },
      { name: "Navy", hex: "#1B2838" },
    ],
    stock: 21,
    isPopular: true,
    viewsCount: 178,
    boughtToday: 7,
  },
  {
    name: { ru: "Набор Pocket Square", tj: "Маҷmӯa Pocket Square" },
    description: {
      ru: "Набор из 3 платков для пиджака. Шёлк и лён, подарочная коробка Golib.",
      tj: "Мajmӯa аз 3 платок барои курta. Абр ва катon.",
    },
    category: "accessories",
    brand: "Golib",
    price: 450,
    images: [
      "https://images.unsplash.com/photo-1617137968427-85924c800a41?w=800&q=80",
      "https://images.unsplash.com/photo-1624227732930-1c8a28058103?w=800&q=80",
    ],
    sizes: ["One Size"],
    colors: [{ name: "Assorted", hex: "#4A5568" }],
    stock: 27,
    isNew: true,
    viewsCount: 89,
  },
];

const allSeeds: ProductSeed[] = [
  ...sets,
  ...tShirts,
  ...shirts,
  ...pants,
  ...shoes,
  ...accessories,
];

export const catalogProductSeeds: Product[] = withGuaranteedImages(
  allSeeds.map((product, index) => {
    const id = String(index + 1);
    const slugPart = slugify(product.name.ru) || String((index % 10) + 1);
    return {
      ...product,
      id,
      slug: `${product.category}-${slugPart}`,
      sku: `GLB-${1000 + index}`,
    };
  })
);
